---
title: "IN4400 Assignment 3"
author: "Balázs Dukai | 4516001"
date: "October 17, 2015"
output: pdf_document
classoption: a4paper
documentclass: report
csl: csl/apa-single-spaced.csl
bibliography: IN4400.bib
---

# TODOs

1. Make Figure 1 and review 1st paragraph.

    + Figure 1:  Asylum applications (non-EU) in the EU-28 Member States, 2004–2014
    
2. Pimp map


# Introduction

Due to the crisis in the Middle East and North-Africa people were and are forced to leave their home, heading towards Europe in hope of a better life. Thus in the last couple of years, especially in the second quarter of 2014 and in 2015, the number of people applying for asylum in Europe increased. In the spring and summer of 2015, even increased amount of people started moving to Europe. **Figure 1** shows the increase in the number of first time asylum appications in the EU–28 states between Q2 2014 and Q2 2015.

The EU and its member states were not prepared for such level of immigration, hence these countries faced infrastructural, governmental and societal problems. People living along the main transit routes were directly affected by the flood of refugees. These events gained a huge media coverage, both in social and broadcasted media. Many of us in Europe had an opinion based on the numbers and figures presented in the media. Altough as it is in events too, these numbers and figures can be confusing or misleading. Therefore I wanted to take a look on what data is available and what does it say about this topic. 

In the following lines I am going to focus on answering the questions, such as:

1. From which countries did most of the refugees come from?

2. Which were their main destination countries in this time frame?

3. How is the refugee to citizen ratio in the main destination countires by the end of Q2 2015?

*4. How strong is each destination country in giving social help?*

### Who is a refugee?

The Geneva Convention on Refugees[@unitednations_convention_1951] defines a refugee as a person who is outside of their own country and has well-founded fear of being prosecuted for reasons of race, religion, nationality, membership of a particular social group or political opinion, and due to this fear this person is unwilling to avail himself of the protection of his country, neither wants to return to it.

Clearly this definition doesn't include people who fled their country due to a severe economic or environmental crisis. In 1951 the impacts of global warming were much less understood. Because according this definition, part of the political debate in the EU in the last time was to determine who is eligible for asylum depending on their country of origin, or who is considered as economic or environmental migrant. The Wikipedia article on refugees gives a good overview on the common cagetgories [@_refugee_2015]. For the sake of simplicity I make no distinction between the three and refer to both categories as refugees. 


## Data sources

**eurostat**
Eurostat is the statistical office of the European Union, hence the official source of various european data. The *Asylum and managed migration [@_database]* database is my main data source. The *Asylum quarterly report [@_asylum]* provides an already aggregated report on the first time asylum applicants in Europe. 

# Tools of the trade

My prerequisite was that both data and software has to be open, resp. open source. All the above mentioned data sources satisfy this criteria, and on the software side my workflow looked roughly like this:

1. Data preparation and processing

    + LibreOffice

2. Data visualisation

    + QGIS for the map
    + R for the graphs
    
# 

### The main destination countries [^bla]
"The highest number of first time asylum applicants in the second quarter of 2015 was registeredin Germany (80 900 applicants, or 38% of total applicants in the EU), Hungary (32 700, or 15%), Austria (17 400, or 8%), Italy, France and Sweden (respectively 14 900, 14 700 and 14 300, or 7% each). These 6 Member States together account for more than 80% of all first applicants in the EU-28 (Table 2)." [http://ec.europa.eu/eurostat/statistics-explained/index.php/Asylum_quarterly_report#Main_destination_countries]

### The main departure countries [^1]
"Citizens of 141 countries sought asylum for the first time in the EU in the second quarter of 2015. Syrians, Afghanis and Albanians were the top 3 citizenships of asylum seekers, lodging around 44 000, 27 000 and 17 700 applications respectively (Table 1)."[http://ec.europa.eu/eurostat/statistics-explained/index.php/Asylum_quarterly_report#Main_destination_countries]


the difference between the the educational level in the main emmigration countries and the main immigration countries

## But what does this all mean for the welcoming countries?

# Analysis

Graduates from tertiary education (both sexes)

# Conclusion



# Appendix

## Where does the data come from

### World Bank [http://data.worldbank.org/]
**Syrian Arab Republic**
Population numbers between 2011–2013 are adjusted for Syrian refugees.

+ The UN Refugee Agency [http://www.unhcr.org/pages/49c3646c4d6.html]
+ World Bank – Refugee population by country or territory of asylum [http://data.worldbank.org/indicator/SM.POP.REFG]
+ UN Table Data on Refugees [http://data.un.org/Data.aspx?d=UNHCR&f=indID%3AType-Ref]
+ eurostat – Asylum Statistics [1] [http://ec.europa.eu/eurostat/statistics-explained/index.php/Asylum_statistics]
+ Education Index – UNDP
[http://hdr.undp.org/en/content/education-index]
+ Education – World Bank
[http://data.worldbank.org/topic/education]

1. List of the main emmigration and european immigration countries

2. Census data of the relevant countries 

3. educational indexes of the relevant countries 

    + distribution of elementary, high school, university education –> if all levels of the society is equally affected by war / economic crisis, I can just extrapolate this distribution  to the refugees to determine who came


## Code

# References